name: CI
on:
    push:
        branches:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 9
            - uses: actions/setup-node@v4
              with:
                  cache: 'pnpm'
                  node-version: '20.x'

            - run: pnpm install --frozen-lockfile
            - run: pnpm run lint && pnpm run build
